# Generated by Django 3.0.8 on 2021-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcreator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appid',
        ),
        migrations.AddField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
